/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 非现场监管微信服务 API - version 0.0.1
 *
 * 基于微信小程序的非现场监管管理服务接口文档
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.checkClockRangeUsingPOST': ['POST', '/maintenanceClock/checkClockRange'],
  'general.currRecordUsingGET': ['GET', '/maintenanceClock/currRecord'],
  'general.endMaintenanceUsingPOST': ['POST', '/maintenanceClock/end'],
  'general.getMyRecordsUsingGET': ['GET', '/maintenanceClock/myRecords'],
  'general.startMaintenanceUsingPOST': ['POST', '/maintenanceClock/start'],
  'general.getStatisticsUsingGET': ['GET', '/maintenancePerson/statistics'],
  'general.getMyMaintenanceTasksUsingGET': ['GET', '/maintenanceTask/myTasks'],
  'general.getTaskStatisticsUsingGET': ['GET', '/maintenanceTask/statistics'],
  'general.getMaintenanceTaskByIdUsingGET': ['GET', '/maintenanceTask/taskDetail'],
  'general.decodeUserUsingPOST': ['POST', '/wcaUser/decodeUser']
};
