/* tslint:disable */
/* eslint-disable */
/**
 * 非现场监管微信服务 API - version 0.0.1
 *
 * 基于微信小程序的非现场监管管理服务接口文档
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface CheckClockRangeRequestVO {
  /**
   * 纬度
   */
  latitude: number;
  /**
   * 经度
   */
  longitude: number;
  /**
   * 维保任务ID
   */
  rwid: string;
}
export interface MaintenanceEndRequestVO {
  /**
   * 打卡ID
   */
  dkid: string;
}
export interface MaintenanceStartRequestVO {
  /**
   * 维保任务ID
   */
  rwid?: string;
}
export interface DecodeUserRequestVO {
  /**
   * 通过前端获取的临时登录凭证
   */
  code?: string;
  /**
   * 加密数据
   */
  encryptedData?: string;
  /**
   * 解密算法初始向量
   */
  iv?: string;
}
export interface PersonStatisticsVO {
  /**
   * 本月打卡时长（h）
   */
  monthClockHours?: number;
  /**
   * 本月已完成任务数
   */
  monthCompletedCount?: number;
  /**
   * 本月未完成任务数
   */
  monthUncompletedCount?: number;
  /**
   * 本年打卡时长（h）
   */
  yearClockHours?: number;
  /**
   * 本年已完成任务数
   */
  yearCompletedCount?: number;
}
export interface _PersonStatisticsVO_ {
  /**
   * 代码
   */
  code?: string;
  /**
   * PersonStatisticsVO
   * ---
   * 个人打卡统计
   */
  data?: PersonStatisticsVO;
  /**
   * 提示消息
   */
  msg?: object;
}
export interface TaskStatisticsVO {
  /**
   * 已完成任务数量
   */
  completedCount?: number;
  /**
   * 待处理任务数量
   */
  pendingCount?: number;
  /**
   * 处理中任务数量
   */
  processingCount?: number;
  /**
   * 总任务数量
   */
  totalCount?: number;
}
export interface _TaskStatisticsVO_ {
  /**
   * 代码
   */
  code?: string;
  /**
   * TaskStatisticsVO
   * ---
   * 任务统计VO
   */
  data?: TaskStatisticsVO;
  /**
   * 提示消息
   */
  msg?: object;
}
export interface _boolean_ {
  /**
   * 代码
   */
  code?: string;
  /**
   * 数据
   */
  data?: boolean;
  /**
   * 提示消息
   */
  msg?: object;
}
export interface SrvcMaintenanceClockVO {
  /**
   * 打卡ID
   */
  dkid?: string;
  /**
   * 单位ID，引用srvc_electronic_fence.dwid
   */
  dwid?: string;
  /**
   * 单位名称
   */
  dwmc?: string;
  /**
   * 维保任务ID，引用srvc_maintenance_tasklist.rwid
   */
  rwid?: string;
  /**
   * 手机号码, 引用srvc_maintenance_personinfo.sjhm
   */
  sjhm?: string;
  /**
   * 维保结束时间（打卡结束时间）
   */
  wbjssj?: string;
  /**
   * 维保开始时间（打卡开始时间）
   */
  wbkssj?: string;
  /**
   * 维保人员ID，引用srvc_maintenance_personinfo.wbryid
   */
  wbryid?: string;
  /**
   * 维保人员姓名
   */
  wbryxm?: string;
}
export interface _SrvcMaintenanceClockVO_ {
  /**
   * 代码
   */
  code?: string;
  /**
   * SrvcMaintenanceClockVO
   * ---
   * 维保打卡记录表(南宁维保模块)VO
   */
  data?: SrvcMaintenanceClockVO;
  /**
   * 提示消息
   */
  msg?: object;
}
export interface IPage_SrvcMaintenanceClockVO_ {
  current?: number;
  pages?: number;
  records?: SrvcMaintenanceClockVO[];
  searchCount?: boolean;
  size?: number;
  total?: number;
}
export interface _IPage_SrvcMaintenanceClockVO_ {
  /**
   * 代码
   */
  code?: string;
  /**
   * IPage«SrvcMaintenanceClockVO»
   * ---
   */
  data?: IPage_SrvcMaintenanceClockVO_;
  /**
   * 提示消息
   */
  msg?: object;
}
export interface MaintenanceTaskVO {
  /**
   * 单位ID
   */
  dwid?: string;
  /**
   * 单位名称
   */
  dwmc?: string;
  /**
   * 短信下发时间（任务下发时间）
   */
  dxxfsj?: string;
  /**
   * 任务处理状态：0待处理, 1处理中, 2已完成
   */
  rwclzt?: number;
  /**
   * 任务ID
   */
  rwid?: string;
  /**
   * 维保地址
   */
  wbdz?: string;
  /**
   * 终端单位类型列表:1高层建筑，2地下建筑，3大型综合体，4大型化工单位，5住宅小区，6自建房，7重点单位
   */
  zddwlxList?: number[];
}
export interface IPage_MaintenanceTaskVO_ {
  current?: number;
  pages?: number;
  records?: MaintenanceTaskVO[];
  searchCount?: boolean;
  size?: number;
  total?: number;
}
export interface _IPage_MaintenanceTaskVO_ {
  /**
   * 代码
   */
  code?: string;
  /**
   * IPage«MaintenanceTaskVO»
   * ---
   */
  data?: IPage_MaintenanceTaskVO_;
  /**
   * 提示消息
   */
  msg?: object;
}
export interface _MaintenanceTaskVO_ {
  /**
   * 代码
   */
  code?: string;
  /**
   * MaintenanceTaskVO
   * ---
   * 维保任务VO
   */
  data?: MaintenanceTaskVO;
  /**
   * 提示消息
   */
  msg?: object;
}
export interface SrvcMaintenancePersoninfoVO {
  /**
   * 出生日期
   */
  csrq?: string;
  /**
   * 地址
   */
  dz?: string;
  /**
   * 公民身份证号码
   */
  gmsfzhm?: string;
  /**
   * 手机号码
   */
  sjhm?: string;
  /**
   * 维保人员ID
   */
  wbryid?: string;
  /**
   * 维保人员姓名
   */
  wbryxm?: string;
  /**
   * 性别
   */
  xb?: string;
  /**
   * 邮箱地址
   */
  yxdz?: string;
  /**
   * 证书编号
   */
  zsbh?: string;
  /**
   * 证书等级
   */
  zsdj?: string;
  /**
   * 证书名称
   */
  zsmc?: string;
}
export interface DecodeUserResponseVO {
  /**
   * openId
   */
  openId?: string;
  /**
   * 完整手机号，包含国家 / 地区代码（如中国为 +86）
   */
  phoneNumber?: string;
  /**
   * 纯手机号，不包含国家 / 地区代码，仅保留本地号码部分（国内用户即 11 位手机号）
   */
  purePhoneNumber?: string;
  /**
   * token，后续所有请求需要带上该参数
   */
  token?: string;
  /**
   * SrvcMaintenancePersoninfoVO
   * ---
   * 维保人员信息表(南宁维保模块)VO
   */
  user?: SrvcMaintenancePersoninfoVO;
}
export interface _DecodeUserResponseVO_ {
  /**
   * 代码
   */
  code?: string;
  /**
   * DecodeUserResponseVO
   * ---
   * 用户信息解码返回VO
   */
  data?: DecodeUserResponseVO;
  /**
   * 提示消息
   */
  msg?: object;
}
declare global {
  interface Apis {
    general: {
      /**
       * ---
       *
       * [POST] 检查是否在打卡范围
       *
       * **path:** /maintenanceClock/checkClockRange
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 纬度
       *   latitude: number
       *   // 经度
       *   longitude: number
       *   // 维保任务ID
       *   rwid: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 代码
       *   code?: string
       *   // 数据
       *   data?: boolean
       *   // 提示消息
       *   msg?: object
       * }
       * ```
       */
      checkClockRangeUsingPOST<
        Config extends Alova2MethodConfig<_boolean_> & {
          data: CheckClockRangeRequestVO;
        }
      >(
        config: Config
      ): Alova2Method<_boolean_, 'general.checkClockRangeUsingPOST', Config>;
      /**
       * ---
       *
       * [GET] 当前任务打卡记录
       *
       * **path:** /maintenanceClock/currRecord
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 任务ID
       *   rwid: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 代码
       *   code?: string
       *   // [title] SrvcMaintenanceClockVO
       *   // 维保打卡记录表(南宁维保模块)VO
       *   data?: {
       *     // 打卡ID
       *     dkid?: string
       *     // 单位ID，引用srvc_electronic_fence.dwid
       *     dwid?: string
       *     // 单位名称
       *     dwmc?: string
       *     // 维保任务ID，引用srvc_maintenance_tasklist.rwid
       *     rwid?: string
       *     // 手机号码, 引用srvc_maintenance_personinfo.sjhm
       *     sjhm?: string
       *     // 维保结束时间（打卡结束时间）
       *     wbjssj?: string
       *     // 维保开始时间（打卡开始时间）
       *     wbkssj?: string
       *     // 维保人员ID，引用srvc_maintenance_personinfo.wbryid
       *     wbryid?: string
       *     // 维保人员姓名
       *     wbryxm?: string
       *   }
       *   // 提示消息
       *   msg?: object
       * }
       * ```
       */
      currRecordUsingGET<
        Config extends Alova2MethodConfig<_SrvcMaintenanceClockVO_> & {
          params: {
            /**
             * 任务ID
             */
            rwid: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<_SrvcMaintenanceClockVO_, 'general.currRecordUsingGET', Config>;
      /**
       * ---
       *
       * [POST] 结束维保
       *
       * **path:** /maintenanceClock/end
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 打卡ID
       *   dkid: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 代码
       *   code?: string
       *   // [title] SrvcMaintenanceClockVO
       *   // 维保打卡记录表(南宁维保模块)VO
       *   data?: {
       *     // 打卡ID
       *     dkid?: string
       *     // 单位ID，引用srvc_electronic_fence.dwid
       *     dwid?: string
       *     // 单位名称
       *     dwmc?: string
       *     // 维保任务ID，引用srvc_maintenance_tasklist.rwid
       *     rwid?: string
       *     // 手机号码, 引用srvc_maintenance_personinfo.sjhm
       *     sjhm?: string
       *     // 维保结束时间（打卡结束时间）
       *     wbjssj?: string
       *     // 维保开始时间（打卡开始时间）
       *     wbkssj?: string
       *     // 维保人员ID，引用srvc_maintenance_personinfo.wbryid
       *     wbryid?: string
       *     // 维保人员姓名
       *     wbryxm?: string
       *   }
       *   // 提示消息
       *   msg?: object
       * }
       * ```
       */
      endMaintenanceUsingPOST<
        Config extends Alova2MethodConfig<_SrvcMaintenanceClockVO_> & {
          data: MaintenanceEndRequestVO;
        }
      >(
        config: Config
      ): Alova2Method<_SrvcMaintenanceClockVO_, 'general.endMaintenanceUsingPOST', Config>;
      /**
       * ---
       *
       * [GET] 历史维保记录
       *
       * **path:** /maintenanceClock/myRecords
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 当前页码
       *   current?: null
       *   // 每页条数
       *   size?: null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 代码
       *   code?: string
       *   // [title] IPage«SrvcMaintenanceClockVO»
       *   data?: {
       *     current?: number
       *     pages?: number
       *     // [items] start
       *     // [title] SrvcMaintenanceClockVO
       *     // 维保打卡记录表(南宁维保模块)VO
       *     // [items] end
       *     records?: Array<{
       *       // 打卡ID
       *       dkid?: string
       *       // 单位ID，引用srvc_electronic_fence.dwid
       *       dwid?: string
       *       // 单位名称
       *       dwmc?: string
       *       // 维保任务ID，引用srvc_maintenance_tasklist.rwid
       *       rwid?: string
       *       // 手机号码, 引用srvc_maintenance_personinfo.sjhm
       *       sjhm?: string
       *       // 维保结束时间（打卡结束时间）
       *       wbjssj?: string
       *       // 维保开始时间（打卡开始时间）
       *       wbkssj?: string
       *       // 维保人员ID，引用srvc_maintenance_personinfo.wbryid
       *       wbryid?: string
       *       // 维保人员姓名
       *       wbryxm?: string
       *     }>
       *     searchCount?: boolean
       *     size?: number
       *     total?: number
       *   }
       *   // 提示消息
       *   msg?: object
       * }
       * ```
       */
      getMyRecordsUsingGET<
        Config extends Alova2MethodConfig<_IPage_SrvcMaintenanceClockVO_> & {
          params: {
            /**
             * 当前页码
             */
            current?: number;
            /**
             * 每页条数
             */
            size?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<_IPage_SrvcMaintenanceClockVO_, 'general.getMyRecordsUsingGET', Config>;
      /**
       * ---
       *
       * [POST] 开始维保
       *
       * **path:** /maintenanceClock/start
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 维保任务ID
       *   rwid?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 代码
       *   code?: string
       *   // [title] SrvcMaintenanceClockVO
       *   // 维保打卡记录表(南宁维保模块)VO
       *   data?: {
       *     // 打卡ID
       *     dkid?: string
       *     // 单位ID，引用srvc_electronic_fence.dwid
       *     dwid?: string
       *     // 单位名称
       *     dwmc?: string
       *     // 维保任务ID，引用srvc_maintenance_tasklist.rwid
       *     rwid?: string
       *     // 手机号码, 引用srvc_maintenance_personinfo.sjhm
       *     sjhm?: string
       *     // 维保结束时间（打卡结束时间）
       *     wbjssj?: string
       *     // 维保开始时间（打卡开始时间）
       *     wbkssj?: string
       *     // 维保人员ID，引用srvc_maintenance_personinfo.wbryid
       *     wbryid?: string
       *     // 维保人员姓名
       *     wbryxm?: string
       *   }
       *   // 提示消息
       *   msg?: object
       * }
       * ```
       */
      startMaintenanceUsingPOST<
        Config extends Alova2MethodConfig<_SrvcMaintenanceClockVO_> & {
          data: MaintenanceStartRequestVO;
        }
      >(
        config: Config
      ): Alova2Method<_SrvcMaintenanceClockVO_, 'general.startMaintenanceUsingPOST', Config>;
      /**
       * ---
       *
       * [GET] 个人打卡统计
       *
       * **path:** /maintenancePerson/statistics
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 代码
       *   code?: string
       *   // [title] PersonStatisticsVO
       *   // 个人打卡统计
       *   data?: {
       *     // 本月打卡时长（h）
       *     monthClockHours?: number
       *     // 本月已完成任务数
       *     monthCompletedCount?: number
       *     // 本月未完成任务数
       *     monthUncompletedCount?: number
       *     // 本年打卡时长（h）
       *     yearClockHours?: number
       *     // 本年已完成任务数
       *     yearCompletedCount?: number
       *   }
       *   // 提示消息
       *   msg?: object
       * }
       * ```
       */
      getStatisticsUsingGET<Config extends Alova2MethodConfig<_PersonStatisticsVO_>>(
        config?: Config
      ): Alova2Method<_PersonStatisticsVO_, 'general.getStatisticsUsingGET', Config>;
      /**
       * ---
       *
       * [GET] 我的维保任务（分页）
       *
       * **path:** /maintenanceTask/myTasks
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 当前页码
       *   current?: number
       *   // 每页数量
       *   size?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 代码
       *   code?: string
       *   // [title] IPage«MaintenanceTaskVO»
       *   data?: {
       *     current?: number
       *     pages?: number
       *     // [items] start
       *     // [title] MaintenanceTaskVO
       *     // 维保任务VO
       *     // [items] end
       *     records?: Array<{
       *       // 单位ID
       *       dwid?: string
       *       // 单位名称
       *       dwmc?: string
       *       // 短信下发时间（任务下发时间）
       *       dxxfsj?: string
       *       // 任务处理状态：0待处理, 1处理中, 2已完成
       *       rwclzt?: number
       *       // 任务ID
       *       rwid?: string
       *       // 维保地址
       *       wbdz?: string
       *       // 终端单位类型列表:1高层建筑，2地下建筑，3大型综合体，4大型化工单位，5住宅小区，6自建房，7重点单位
       *       // [items] start
       *       // [items] end
       *       zddwlxList?: number[]
       *     }>
       *     searchCount?: boolean
       *     size?: number
       *     total?: number
       *   }
       *   // 提示消息
       *   msg?: object
       * }
       * ```
       */
      getMyMaintenanceTasksUsingGET<
        Config extends Alova2MethodConfig<_IPage_MaintenanceTaskVO_> & {
          params: {
            /**
             * 当前页码
             */
            current?: number;
            /**
             * 每页数量
             */
            size?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<_IPage_MaintenanceTaskVO_, 'general.getMyMaintenanceTasksUsingGET', Config>;
      /**
       * ---
       *
       * [GET] 按状态统计我的任务数量
       *
       * **path:** /maintenanceTask/statistics
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 代码
       *   code?: string
       *   // [title] TaskStatisticsVO
       *   // 任务统计VO
       *   data?: {
       *     // 已完成任务数量
       *     completedCount?: number
       *     // 待处理任务数量
       *     pendingCount?: number
       *     // 处理中任务数量
       *     processingCount?: number
       *     // 总任务数量
       *     totalCount?: number
       *   }
       *   // 提示消息
       *   msg?: object
       * }
       * ```
       */
      getTaskStatisticsUsingGET<Config extends Alova2MethodConfig<_TaskStatisticsVO_>>(
        config?: Config
      ): Alova2Method<_TaskStatisticsVO_, 'general.getTaskStatisticsUsingGET', Config>;
      /**
       * ---
       *
       * [GET] 根据任务ID查询维保任务详情
       *
       * **path:** /maintenanceTask/taskDetail
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 任务ID
       *   rwid: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 代码
       *   code?: string
       *   // [title] MaintenanceTaskVO
       *   // 维保任务VO
       *   data?: {
       *     // 单位ID
       *     dwid?: string
       *     // 单位名称
       *     dwmc?: string
       *     // 短信下发时间（任务下发时间）
       *     dxxfsj?: string
       *     // 任务处理状态：0待处理, 1处理中, 2已完成
       *     rwclzt?: number
       *     // 任务ID
       *     rwid?: string
       *     // 维保地址
       *     wbdz?: string
       *     // 终端单位类型列表:1高层建筑，2地下建筑，3大型综合体，4大型化工单位，5住宅小区，6自建房，7重点单位
       *     // [items] start
       *     // [items] end
       *     zddwlxList?: number[]
       *   }
       *   // 提示消息
       *   msg?: object
       * }
       * ```
       */
      getMaintenanceTaskByIdUsingGET<
        Config extends Alova2MethodConfig<_MaintenanceTaskVO_> & {
          params: {
            /**
             * 任务ID
             */
            rwid: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<_MaintenanceTaskVO_, 'general.getMaintenanceTaskByIdUsingGET', Config>;
      /**
       * ---
       *
       * [POST] 微信小程序解密用户敏感数据
       *
       * **path:** /wcaUser/decodeUser
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 通过前端获取的临时登录凭证
       *   code?: string
       *   // 加密数据
       *   encryptedData?: string
       *   // 解密算法初始向量
       *   iv?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 代码
       *   code?: string
       *   // [title] DecodeUserResponseVO
       *   // 用户信息解码返回VO
       *   data?: {
       *     // openId
       *     openId?: string
       *     // 完整手机号，包含国家 / 地区代码（如中国为 +86）
       *     phoneNumber?: string
       *     // 纯手机号，不包含国家 / 地区代码，仅保留本地号码部分（国内用户即 11 位手机号）
       *     purePhoneNumber?: string
       *     // token，后续所有请求需要带上该参数
       *     token?: string
       *     // [title] SrvcMaintenancePersoninfoVO
       *     // 维保人员信息表(南宁维保模块)VO
       *     user?: {
       *       // 出生日期
       *       csrq?: string
       *       // 地址
       *       dz?: string
       *       // 公民身份证号码
       *       gmsfzhm?: string
       *       // 手机号码
       *       sjhm?: string
       *       // 维保人员ID
       *       wbryid?: string
       *       // 维保人员姓名
       *       wbryxm?: string
       *       // 性别
       *       xb?: string
       *       // 邮箱地址
       *       yxdz?: string
       *       // 证书编号
       *       zsbh?: string
       *       // 证书等级
       *       zsdj?: string
       *       // 证书名称
       *       zsmc?: string
       *     }
       *   }
       *   // 提示消息
       *   msg?: object
       * }
       * ```
       */
      decodeUserUsingPOST<
        Config extends Alova2MethodConfig<_DecodeUserResponseVO_> & {
          data: DecodeUserRequestVO;
        }
      >(
        config: Config
      ): Alova2Method<_DecodeUserResponseVO_, 'general.decodeUserUsingPOST', Config>;
    };
  }

  var Apis: Apis;
}
